### ISSUE TITLE
Attempting to run preview or build with 1.61 throws a null pointer

### ISSUE THREAD

**Issue by MrLar** [testingisdocumenting/znai#1020]
Attempting to run our current wiki project throws a null pointer error in pretty much every/any plugin.

The following happens:
```
Caused by: java.lang.RuntimeException: error handling include plugin <table>
  free param: assets/misc/perms/basic-perms.json
  opts: {"mappingPath":"assets/misc/yes-no-mapping.csv","Mantaro":{"width":80,"align":"center"},"User":{"width":80,"align":"center"},"Permission Name":{"align":"center"}}

Cannot invoke "org.testingisdocumenting.znai.structure.TocItem.isIndex()" because the return value of "org.testingisdocumenting.znai.structure.TableOfContents.findTocItem(java.nio.file.Path)" is null

        at org.testingisdocumenting.znai.parser.commonmark.MarkdownVisitor.handleIncludePlugin(MarkdownVisitor.java:224)
        at org.testingisdocumenting.znai.parser.commonmark.MarkdownVisitor.visit(MarkdownVisitor.java:148)
        at org.testingisdocumenting.znai.parser.commonmark.include.IncludeBlock.accept(IncludeBlock.java:43)
        at znaishaded.org.commonmark.node.AbstractVisitor.visitChildren(AbstractVisitor.java:137)
        at znaishaded.org.commonmark.node.AbstractVisitor.visit(AbstractVisitor.java:28)
        at znaishaded.org.commonmark.node.Document.accept(Document.java:7)
        at org.testingisdocumenting.znai.parser.commonmark.MarkdownParser.parsePartial(MarkdownParser.java:92)
        at org.testingisdocumenting.znai.parser.commonmark.MarkdownParser.parse(MarkdownParser.java:64)
        at org.testingisdocumenting.znai.website.WebSite.parseMarkupAndUpdateTocItemAndSearch(WebSite.java:525)
        ... 10 more

```

Removing the plugin in the stack-trace above simply causes the error to happen in another plugin.

**Comment by MykolaGolubyev** [comment]
@MrLar thanks for the report! It is a regression. Patch will come out soon.

**Comment by MykolaGolubyev** [comment]
try 1.61.1

**Comment by MykolaGolubyev** [comment]
@MrLar when you have time please try and confirm 1.61.1 works for you

**Comment by MrLar** [comment]
I didn't really get around to it until now but works fine with 1.61.1 :+1:

**Comment by MykolaGolubyev** [comment]
@MrLar thank you for confirmation. 
Any chance I can interest you in end-to-end testing framework for the bot API? That is assuming you use REST API

**Comment by MrLar** [comment]
We aren't really documenting an API nor do we use REST, if that is what you mean, so I don't think that'll be something we can do.
