### ISSUE TITLE
include-open-api plugin doesn't understand `basePath`.

### ISSUE THREAD

**Issue by byc1234** [testingisdocumenting/znai#1070]
When `path` includes `basePath`("path":"/rest/api/whoami") in the plugin, --preview throws the below exception.
If I don't include `basePath`("path":"/api/whoami") in the plugin, --preview doesn't throw an exception.
Here are a stack trace, swagger.json and index.md.

```
Exception in thread "main" java.lang.RuntimeException: 
markup parsing error:
    TOC item: /index
    full path: /home/hwansoo/workspace/test/znai/index.md

java.lang.RuntimeException: cannot find operation: get /rest/api/whoami

	at org.testingisdocumenting.znai.website.WebSite.throwParsingErrorMessage(WebSite.java:555)
	at org.testingisdocumenting.znai.website.WebSite.parseMarkupAndUpdateTocItemAndSearch(WebSite.java:547)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
	at org.testingisdocumenting.znai.website.WebSite.parseMarkups(WebSite.java:489)
	at org.testingisdocumenting.znai.website.WebSite.parse(WebSite.java:188)
	at org.testingisdocumenting.znai.website.WebSite.parseAndDeploy(WebSite.java:175)
	at org.testingisdocumenting.znai.website.WebSite$Configuration.deployTo(WebSite.java:1023)
	at org.testingisdocumenting.znai.cli.ZnaiCliApp.generateDocs(ZnaiCliApp.java:193)
	at org.testingisdocumenting.znai.cli.ZnaiCliApp.start(ZnaiCliApp.java:96)
	at org.testingisdocumenting.znai.cli.ZnaiCliApp.start(ZnaiCliApp.java:67)
	at com.twosigma.testing.documenting.TsDocumentationCliApp.main(TsDocumentationCliApp.java:69)
Caused by: java.lang.RuntimeException: error handling include plugin <open-api>
  free param: swagger.json
  opts: {"method":"get","path":"/rest/api/whoami","autoSection":true}

cannot find operation: get /rest/api/whoami
```

`swagger.json `
```
{
  "consumes": [
    "application/json"
  ],
  "definitions": {
    "Error": {
      "properties": {
        "errors": {
          "type": "object"
        },
        "message": {
          "type": "string"
        }
      },
      "required": [
        "message"
      ],
      "title": "Error",
      "type": "object"
    },
    "User": {
      "description": "A User model.",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ],
      "title": "User",
      "type": "object"
    }
  },
  "host": "localhost",
  "info": {
    "description": "HelloApp API description goes here.",
    "title": "HelloApp API",
    "version": "1.0.0"
  },
  "paths": {
    "/api/whoami": {
      "get": {
        "description": "Return the user the request was authenticated as (HTTP REMOTE_USER).",
        "operationId": "whoami",
        "responses": {
          "200": {
            "description": "A User model.",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        },
        "tags": [
          "whoami"
        ]
      }
    }
  },
  "produces": [
    "application/json"
  ],
  "schemes": [],
  "basePath": "/rest",
  "securityDefinitions": {},
  "swagger": "2.0"
}
```
`index.md`
``` 
# Your product

:include-open-api: swagger.json {method: "get", path: "/rest/api/whoami", autoSection: true}
```

**Comment by MykolaGolubyev** [comment]
As a workaround for now, are you able to render it using operationId?

**Comment by byc1234** [comment]
```
$ cat index.md 
# Your product

:include-open-api: swagger.json {method: "get", operationId: "/rest/api/whoami", autoSection: true}
```
```
parsing index.md
Exception in thread "main" java.lang.RuntimeException: 
markup parsing error:
    TOC item: /index
    full path: /home/hwansoo/workspace/test/znai/index.md

java.lang.IllegalArgumentException: can't find open api operation(s), make sure provided operationId, method, path, tags are set correctly

        at org.testingisdocumenting.znai.website.WebSite.throwParsingErrorMessage(WebSite.java:555)
        at org.testingisdocumenting.znai.website.WebSite.parseMarkupAndUpdateTocItemAndSearch(WebSite.java:547)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
        at org.testingisdocumenting.znai.website.WebSite.parseMarkups(WebSite.java:489)
        at org.testingisdocumenting.znai.website.WebSite.parse(WebSite.java:188)
        at org.testingisdocumenting.znai.website.WebSite.parseAndDeploy(WebSite.java:175)
        at org.testingisdocumenting.znai.website.WebSite$Configuration.deployTo(WebSite.java:1023)
        at org.testingisdocumenting.znai.cli.ZnaiCliApp.generateDocs(ZnaiCliApp.java:193)
        at org.testingisdocumenting.znai.cli.ZnaiCliApp.start(ZnaiCliApp.java:96)
        at org.testingisdocumenting.znai.cli.ZnaiCliApp.start(ZnaiCliApp.java:67)
        at com.twosigma.testing.documenting.TsDocumentationCliApp.main(TsDocumentationCliApp.java:69)
Caused by: java.lang.RuntimeException: error handling include plugin <open-api>
  free param: swagger.json
  opts: {"method":"get","operationId":"/rest/api/whoami","autoSection":true}

can't find open api operation(s), make sure provided operationId, method, path, tags are set correctly

        at org.testingisdocumenting.znai.parser.commonmark.MarkdownVisitor.handleIncludePlugin(MarkdownVisitor.java:221)
        at org.testingisdocumenting.znai.parser.commonmark.MarkdownVisitor.visit(MarkdownVisitor.java:145)
        at org.testingisdocumenting.znai.parser.commonmark.include.IncludeBlock.accept(IncludeBlock.java:43)
        at znaishaded.org.commonmark.node.AbstractVisitor.visitChildren(AbstractVisitor.java:137)
        at znaishaded.org.commonmark.node.AbstractVisitor.visit(AbstractVisitor.java:28)
        at znaishaded.org.commonmark.node.Document.accept(Document.java:7)
        at org.testingisdocumenting.znai.parser.commonmark.MarkdownParser.parsePartial(MarkdownParser.java:89)
        at org.testingisdocumenting.znai.parser.commonmark.MarkdownParser.parse(MarkdownParser.java:61)
        at org.testingisdocumenting.znai.website.WebSite.parseMarkupAndUpdateTocItemAndSearch(WebSite.java:534)
        ... 10 more
Caused by: java.lang.IllegalArgumentException: can't find open api operation(s), make sure provided operationId, method, path, tags are set correctly
        at org.testingisdocumenting.znai.openapi.OpenApi3IncludePlugin.validateOperations(OpenApi3IncludePlugin.java:97)
        at org.testingisdocumenting.znai.openapi.OpenApi3IncludePlugin.process(OpenApi3IncludePlugin.java:88)
        at org.testingisdocumenting.znai.extensions.TrackingIncludePlugin.process(TrackingIncludePlugin.java:65)
        at org.testingisdocumenting.znai.parser.commonmark.MarkdownVisitor.handleIncludePlugin(MarkdownVisitor.java:217)
        ... 18 more
```
operationId returns a different exception.

**Comment by MykolaGolubyev** [comment]
Remove method param and use    operationId: "whoami" (defined in your json)

**Comment by byc1234** [comment]
swagger.json is a auto generated file.

**Comment by byc1234** [comment]
```
Exception in thread "main" java.lang.RuntimeException: 
markup parsing error:
    TOC item: /index
    full path: /home/hwansoo/workspace/test/znai/index.md

java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "id" is null

        at org.testingisdocumenting.znai.website.WebSite.throwParsingErrorMessage(WebSite.java:555)
        at org.testingisdocumenting.znai.website.WebSite.parseMarkupAndUpdateTocItemAndSearch(WebSite.java:547)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
        at org.testingisdocumenting.znai.website.WebSite.parseMarkups(WebSite.java:489)
        at org.testingisdocumenting.znai.website.WebSite.parse(WebSite.java:188)
        at org.testingisdocumenting.znai.website.WebSite.parseAndDeploy(WebSite.java:175)
        at org.testingisdocumenting.znai.website.WebSite$Configuration.deployTo(WebSite.java:1023)
        at org.testingisdocumenting.znai.cli.ZnaiCliApp.generateDocs(ZnaiCliApp.java:193)
        at org.testingisdocumenting.znai.cli.ZnaiCliApp.start(ZnaiCliApp.java:96)
        at org.testingisdocumenting.znai.cli.ZnaiCliApp.start(ZnaiCliApp.java:67)
        at com.twosigma.testing.documenting.TsDocumentationCliApp.main(TsDocumentationCliApp.java:69)
Caused by: java.lang.RuntimeException: error handling include plugin <open-api>
  free param: swagger.json
  opts: {"operationId":"whoami","autoSection":true}

Cannot invoke "String.isEmpty()" because "id" is null
```
```
$ cat index.md 
# Your product

:include-open-api: swagger.json {operationId: "whoami", autoSection: true}
```
Got an another error.

**Comment by MykolaGolubyev** [comment]
Something fishy is going on. Thanks for checking. Will take a look and try to reproduce.

**Comment by MykolaGolubyev** [comment]
@byc1234 null pointer is because summary field is missing but autoSection: true is set. I am making PR to have a better error message. Still investigating basePath

**Comment by byc1234** [comment]
After removing `autoSection: true`, I don't see NPE.

**Comment by byc1234** [comment]
BTW some swagger.json has multiple operations against the same resource like get /rest/api/user, post /rest/api/user, put /rest/api/user, delete /rest/api/user, etc, so method needs to be used with operationId or path.

**Comment by MykolaGolubyev** [comment]
operationId should be unique. 
method is only required when specify path

**Comment by byc1234** [comment]
Ok, then we need method + path to handle basePath.

**Comment by MykolaGolubyev** [comment]
Yes agree. Next PR should address it. 
In addition to removing autoSection you can make generator of swagger to generate summary field to fix NPE

**Comment by MykolaGolubyev** [comment]
@byc1234 when I go to https://editor.swagger.io and paste your JSON, the method shows up as `/api/whoami`

<img width="857" alt="image" src="https://user-images.githubusercontent.com/11657860/213250289-4aa9b1c3-5be7-4bf3-8257-98d13d8b8930.png">

It works in Znai if you also specify the relative path

**Comment by MykolaGolubyev** [comment]
What do you mean by validation. User should be able to find an operation by method and relative URL. It will not print /rest part though

**Comment by MykolaGolubyev** [comment]
Ah I see. Yeah seems like old znai didn’t behave correctly. I started to use official swagger libraries for parsing. Let me think how to address this.

**Comment by MykolaGolubyev** [comment]
I don't have a good middle ground. Do you have any ideas @byc1234 ?

**Comment by MykolaGolubyev** [comment]
closing as inactive
