### ISSUE TITLE
NoClassDefFoundError: org/apache/commons/io/FileUtils in version 1.57

### ISSUE THREAD

**Issue by adzubla** [testingisdocumenting/znai#906]
I'm running `mvn znai:build` version 1.56 with this configuration, and its ok:
```
<plugin>
    <groupId>org.testingisdocumenting.znai</groupId>
    <artifactId>znai-maven-plugin</artifactId>
    <version>1.56</version>
    <configuration>
        <sourceRoot>${project.basedir}/src/main/docs</sourceRoot>
        <docId>site/docs</docId>
    </configuration>
</plugin>
```

But after upgrading to version 1.57 this error happens:

```
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
        at org.testingisdocumenting.znai.resources.ZipJarFileResourceResolver.lambda$createTempDirectory$2(ZipJarFileResourceResolver.java:139)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 2 more
```

**Comment by MykolaGolubyev** [comment]
do you have `.zip` file reference inside your `lookup-paths`?

**Comment by MykolaGolubyev** [comment]
what java version is your maven setup with?

if you have a chance, could you please have a single pom file like this, then do `mvn znai:new` to generate a dummy docs, and then `mvn clean install` to build them.

```
    <build>
        <plugins>
            <plugin>
                <groupId>org.testingisdocumenting.znai</groupId>
                <artifactId>znai-maven-plugin</artifactId>
                <version>1.47</version>
                <executions>
                    <execution>
                        <id>build</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <docId>investigation</docId>
                    <port>3339</port>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

**Comment by adzubla** [comment]
I'm using Java 17.0.2

(Do you mean version 1.57. ou 1.47???)

**Comment by MykolaGolubyev** [comment]
Oh my bad. Will try later the correct one!

**Comment by MykolaGolubyev** [comment]
This is so weird. I am able to reproduce, but I also see maven build does its job, i.e. docs are generated. Investigating the root cause for the exception

**Comment by adzubla** [comment]
Thanks, I will wait for the next release.

**Comment by MykolaGolubyev** [comment]
Should be released tomorrow. 
Any chance you can share some details on how you use Znai? There is a section under Discussions
