### ISSUE TITLE
Collapsible API-Parameters breaks on tabs

### ISSUE THREAD

**Issue by Haxiz** [testingisdocumenting/znai#957]
If you try to add a collapsible api-parameters inside of a tab, the api-parameter gets eaten and, instead, the title for said api-parameter is added as a tab.

Example:
`````
# /badges
Shows a list of your own badges or a list of the badges from the given user. A full list of the badges can be found [here](currency/badges).

````tabs
Subcommands:
* `Info`: Shows info about a badge.
* `List`: Lists all the obtainable badges.
* `Show`: Show your badge list, or someone else's badge list. 

Options:
```api-parameters {title: "Hello", collapsible: true}
Info, Click me!, "Options for the `Info` Subcommand"
Info.badge, "Required", "The badge to check info for"
Show, Click me!, "Options for the `Show` Subcommand"
Show.user, "Optional", "The user to check. If none, you."
Show.brief, "Optional", "Whether to show this in brief format. Default is false."
```

Requirements:
* This command requires [**Embed**, **Emotes** and **Reactions** permissions](commands/permissions#intro).

Examples:
* /badges show
* /badges show `user:`@Kodehawa#3457
* /badges list
* /badges info `badge:`Donator
````
`````
Result:
![image](https://user-images.githubusercontent.com/31944205/185820890-af05a234-0834-426a-b6b3-7b57cdf2327e.png)
![image](https://user-images.githubusercontent.com/31944205/185821117-f6765caf-8010-4e73-ab3b-138ee3b2ba87.png)

If the `collapsible: true` option is removed however, it works fine.
![image](https://user-images.githubusercontent.com/31944205/185820988-39fdef99-e1f1-458e-915a-bc8e8062c91c.png)

**Comment by MykolaGolubyev** [comment]
This is weird indeed. What happens when you put collapsible option to a new line and put spaces in front of it?

**Comment by Haxiz** [comment]
on a new line
````
Options:
```api-parameters
{title: "Hello", collapsible: true} 
Info, Click me!, "Options for the `Info` Subcommand"
Info.badge, "Required", "The badge to check info for"
Show, Click me!, "Options for the `Show` Subcommand"
Show.user, "Optional", "The user to check. If none, you."
Show.brief, "Optional", "Whether to show this in brief format. Default is false."
```
````
![image](https://user-images.githubusercontent.com/31944205/185821814-826557b5-94ea-489d-a1cf-3133c2ababae.png)
with new line and spaces
````
Options:
```api-parameters
{ title: "Hello", collapsible: true } 
Info, Click me!, "Options for the `Info` Subcommand"
Info.badge, "Required", "The badge to check info for"
Show, Click me!, "Options for the `Show` Subcommand"
Show.user, "Optional", "The user to check. If none, you."
Show.brief, "Optional", "Whether to show this in brief format. Default is false."
```
````
![image](https://user-images.githubusercontent.com/31944205/185821896-6281cc7c-b011-441b-8d8a-ba802799a2af.png)

**Comment by MykolaGolubyev** [comment]
Thanks a bunch 
Will try my best to fix asap and release a patch. Clearly there were no use cases to put api params inside tabs.
We usually don’t use tabs for navigation. More like switching between mediums, Eg CLI vs REST or languages Java vs C++

**Comment by MykolaGolubyev** [comment]
Btw did you see https://testingisdocumenting.org/znai/visuals/headings#heading-types for heading styles?

could be useful when your header is a command or function name

**Comment by Haxiz** [comment]
I didn't! I think i might use those instead. Thanks for the suggestion!

**Comment by MykolaGolubyev** [comment]
@Haxiz could you please confirm what param name do you use for collapsing params? It should be `collapse: true|false` and `collapsible: true` should throw an error.

**Comment by MrLar** [comment]
I work on the same project as hax. I can confirm that neither `collapsible`, `collapse` nor the one [actually outlined in the docs](https://testingisdocumenting.org/znai/snippets/api-parameters#collapsing-parameters) `collapsed` seem to work. They all result in the same behaviour. The culprit here seems to be the `title` as omitting the title simply makes znai not render the param meant to be collapsed, which is intentional since title is required but at least it doesn't break. In neither of these cases it throws any kind of error.

Below is the code we use (it shows all 3 variants but naturally we only chose one at a time).
````tabs
Subcommands:
* `Info`: Shows info about a badge.
* `List`: Lists all the obtainable badges.
* `Show`: Show your badge list, or someone else's badge list. 

Options
```api-parameters {title: "Hello", collapse/collapsible/collabsed: true}
Info, Click me!, "Options for the `Info` Subcommand"
Info.badge, "Required", "The badge to check info for"
Show, Click me!, "Options for the `Show` Subcommand"
Show.user, "Optional", "The user to check. If none, you."
Show.brief, "Optional", "Whether to show this in brief format. Default is false."
```

Requirements:
* This command requires [**Embed**, **Emotes** and **Reactions** permissions](commands/permissions#intro).

Examples:
* /badges show
* /badges show `user:`@Kodehawa#3457
* /badges list
* /badges info `badge:`Donator
````

Additionally the following also results in interesting and unintentional behaviour which might be related:

````tabs
Subcommands:
* `Info`: Shows info about a badge.
* `List`: Lists all the obtainable badges.
* `Show`: Show your badge list, or someone else's badge list. 

Options {title: "a"}:
```api-parameters
Info, Click me!, "Options for the `Info` Subcommand"
Info.badge, "Required", "The badge to check info for"
Show, Click me!, "Options for the `Show` Subcommand"
Show.user, "Optional", "The user to check. If none, you."
Show.brief, "Optional", "Whether to show this in brief format. Default is false."
```

Requirements:
* This command requires [**Embed**, **Emotes** and **Reactions** permissions](commands/permissions#intro).

Examples:
* /badges show
* /badges show `user:`@Kodehawa#3457
* /badges list
* /badges info `badge:`Donator
````
![](https://mrlar.dev/i/KC9Stm765DEkWKnyccDFXkjkpsmWvc.png)

As you can see the `title` replaces the original title for the tab and the colon which is normally part of the syntax is appended as raw text (removing it causes the tab to merge as raw text into the `Subcommands` tab, meaning its "required").

**Comment by MykolaGolubyev** [comment]
oh, ```Options {title: "a"}:``` is an interesting cue. Thanks. PR is being built right now. Should fix that.
@MrLar BTW you adding `title` to tab name, is it by accident or are you trying to achieve something with this?

**Comment by MykolaGolubyev** [comment]
do you have an ability to build znai locally? requires java and maven. 
I plan to release a patch soon as one of the issues fixed recently is a regression. But wonder if you could re-validate my fix

**Comment by MrLar** [comment]
> oh, `Options {title: "a"}:` is an interesting cue. Thanks. PR is being built right now. Should fix that. @MrLar BTW you adding `title` to tab name, is it by accident or are you trying to achieve something with this?

It's simply something I noticed there was no real intention behind it, just messing about trying to find a cause.

**Comment by Haxiz** [comment]
> do you have an ability to build znai locally? requires java and maven. I plan to release a patch soon as one of the issues fixed recently is a regression. But wonder if you could re-validate my fix

sure we'll give it a try and let you know

**Comment by Haxiz** [comment]
@MykolaGolubyev we've been trying to build for a while, however we haven't had any luck with it yet.

Mainly we're currently stuck at maven not resolving a snapshot plugin
![image](https://user-images.githubusercontent.com/31944205/185992347-c68c5e89-c289-457c-b04b-7e0230000db1.png)
We tried `mvn install -U`, however it fails tests
![image](https://user-images.githubusercontent.com/31944205/185993049-771e125b-8c3b-428e-ba5e-cdf68a26322d.png)

trying to build of course didnt work either, as it fails when it cannot resolve the dependency

**Comment by Haxiz** [comment]
The tests that failed from before
```
-------------------------------------------------------------------------------
Test set: org.testingisdocumenting.znai.utils.JsonUtilsTest
-------------------------------------------------------------------------------
Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.157 sec <<< FAILURE!
should serialize json using pretty print(org.testingisdocumenting.znai.utils.JsonUtilsTest)  Time elapsed: 0.006 sec  <<< FAILURE!
Assertion failed: 

assert asText == '{\n' + '  "k1" : "v1",\n' + '  "k2" : [ "v2", "v3" ]\n' + '}'
       |      |        |                    |                             |
       |      false    '{\n  "k1" : "v1",\n'|                             '{\n  "k1" : "v1",\n  "k2" : [ "v2", "v3" ]\n}'
       |                                    '{\n  "k1" : "v1",\n  "k2" : [ "v2", "v3" ]\n'
       '{\r\n  "k1" : "v1",\r\n  "k2" : [ "v2", "v3" ]\r\n}'

	at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:436)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:670)
	at org.testingisdocumenting.znai.utils.JsonUtilsTest.should serialize json using pretty print(JsonUtilsTest.groovy:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```
```
-------------------------------------------------------------------------------
Test set: org.testingisdocumenting.znai.utils.ResourceUtilsTest
-------------------------------------------------------------------------------
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.025 sec <<< FAILURE!
should read text from a single resource file(org.testingisdocumenting.znai.utils.ResourceUtilsTest)  Time elapsed: 0.001 sec  <<< FAILURE!
Assertion failed: 

assert content == "single resource\nfile"
       |       |
       |       false
       'single resource\r\nfile'

	at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:436)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:670)
	at org.testingisdocumenting.znai.utils.ResourceUtilsTest.should read text from a single resource file(ResourceUtilsTest.groovy:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by MykolaGolubyev** [comment]
Thanks for trying! 
you can ignore sync in IDE. 
as for the test failures looks like it has been awhile I built it using windows. 

Don’t want to use more of your time. But just in case, if you ever want to PR windows fix I will be more than happy to merge it. 

Meanwhile I will work on releasing a patch today or tomorrow.

**Comment by MykolaGolubyev** [comment]
released https://testingisdocumenting.org/znai/release-notes/2022/#1591
